spring.application.name=opaque

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/opaque_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.config.import=optional:application-local.properties
